### ISSUE TITLE
Add welcome page

### ISSUE THREAD

**Issue by tcalex43** [bobforcha/lgl_jukebox#15]
Both user and developer want a fast, attractive and responsive welcome page.

**Comment by bobforcha** [comment]
I think we can drop the navbar from the welcome page. We'll just have it throughout the rest of the app. We'll make it look better as well.

Something is messed up in the formatting for the search link, it got moved out of line with the others

**Comment by bobforcha** [comment]
I'm fixing this branch to kinda start the app over. Figured out how to redirect it properly. Gonna write a welcome spec and set it up, nuke the current user set up and start over on that. Top down for reals.

**Comment by bobforcha** [comment]
Crap, I accidentally deleted your work from my machine as well as the repo. My bad. Next time you have access to it, could you email me the welcome page erb file, the pages.scss file, and the 2 images from your machine before pulling anything?

**Comment by tcalex43** [comment]
Sorry bob I went straight to Bri’s page

**Comment by tcalex43** [comment]
body {
    background: rgba(0, 0, 0, 0.9);
    margin: 0;
    color: grey;
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
}

.showcase::after {
    content: '';
    height: 100vh;
    width: 100%;
    background-image: url(\mari.jpg);
    background-size: cover;
    background-repeat: no-repeat;
    background-position: center;
    display: block;
    filter: blur(10px);
    -webkit-filter: blur(10px);
    transition: all 1000ms;
}

.showcase:hover::after {
    filter: blur(0px);
    -webkit-filter: blur(0px);
}

.showcase:hover .content {
    filter: blur(2px);
    -webkit-filter: blur(2px);
}

.content {
    position: absolute;
    z-index: 1;
    top: 10%;
    left: 50%;
    margin-top: 105px;
    margin-left: -145px;
    width: 300px;
    height: 350px;
    text-align: center;
    transition: all 1000ms;
}

.content .logo {
    height: 180px;
    width: 180px;
}

.content .title {
    font-size: 2.5rem;
    margin-top: 2.5rem;
    color: black;
}

.content .text {
    line-height: 1.7;
    margin-top: 1rem;
}

.container {
    max-width: 960px;
    margin: auto;
    overflow: hidden;
    padding: 4rem 1rem;
}

.grid-3 {
    display: grid;
    grid-gap: 20px;
    grid-template-columns: repeat(3, 1fr);
}

.grid-2 {
    display: grid;
    grid-gap: 20px;
    grid-template-columns: repeat(2, 1fr);
}

.center {
    text-align: center;
    margin: auto;
}

.bg-light {
    background: #f4f4f4;
    color: #333;
}

.bg-dark {
    background: #333;
    color: #f4f4f4;
}

footer {
    padding: 2.2rem;
}

footer p {
    margin: 0;
}

/* Small Screens */
@media (max-width: 560px) {
    .showcase::after {
        height: 50vh;
    }

    .content {
        top: 5%;
        margin-top: 5px;
    }

    .content .logo {
        height: 140px;
        width: 140px;
    }

    .content .text {
        display: none;
    }

    .grid-3,
    .grid-2 {
        grid-template-columns: 1fr;
    }

    .services div {
        border-bottom: #333 dashed 1px;
        padding: 1.2rem 1rem;
    }
}

/* Landscape */
@media (max-height: 500px) {

    .content .title,
    .content .text {
        display: none;
    }

    .content {
        top: 0;
    }
}
<!DOCTYPE html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <title>LGL</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="\assets\application.css">
  </head>
 <body>
   
    <header class="showcase">
    <div class="content">
    <%= image_tag("\LogoLGL.jpg", width: '150px') %>
    
      <div class="title">
        Welcome To The Looking Glass Lounge JukeBox
      </div>
      </div>
  </header>

  
  <section class="services">
    <div class="container grid-3 center">
      <div>
      
        <i class="fas fa-user-astronaut fa-3x"></i>
        <h3><%= link_to "Create User", new_user_path %><h3>
        <p>Access Personal Playlist</p>
      </div>
      <div>
        <i class="fas fa-play fa-3x"></i>
        <h3>Now Playing</h3>
        <p>Jump Into The Action</p>
      </div>
      <div>
        <i class="fas fa-search fa-3x"></i>
        <h3>Search</h3>
        <p>Search Music Library</p>
      </div>
    </div>
  </section>

  <footer class="center bg-dark">
    <p>Looking Glass Lounge</p>
  </footer>
    <script src="" async defer></script>
  </body>
</html>

**Comment by tcalex43** [comment]
sorry I'm not thinking straight

**Comment by bobforcha** [comment]
Sweet, mostly got it fixed now
